---

- name: configure_vddk_credentials | Confirm OpenShift Ansible Host Provided
  ansible.builtin.assert:
    that:
      - e2e_testing_openshift_ansible_host | default('', true) | length > 0
    quiet: true
    fail_msg: "OpenShift Ansible Host must be provided."

- name: configure_vddk_credentials | Invoke Registry Credentials Job Template
  ansible.builtin.include_role:
    name: infra.aap_configuration.controller_job_launch
  vars:
    controller_launch_jobs:
      - name: "{{ e2e_testing_openshift_aap_registry_credentials_job_template }}"
        organization: "{{ e2e_testing_openshift_aap_organization }}"
        credentials:
          - "{{ e2e_testing_openshift_ansible_host }}"
        extra_vars:
          utility_registry_credentials_namespace: "{{ e2e_testing_target_namespace }}"
          utility_registry_credentials_secret_name: >-
            {{
              (__e2e_testing_vm_source + '-registry-credentials')
              | infra.openshift_virtualization_migration.rfc1123
            }}
          utility_registry_credentials_registry_host: >-
            {{
              hostvars[__e2e_testing_vm_source]['vddk']['image']
              | split('/') | first
            }}
          utility_registry_credentials_registry_username: "{{ hostvars[__e2e_testing_vm_source]['vddk']['username'] }}"
          utility_registry_credentials_registry_password: "{{ hostvars[__e2e_testing_vm_source]['vddk']['password'] }}"
        wait: true
  loop_control:
    loop_var: __e2e_testing_vm_source
  loop: "{{ hostvars[e2e_testing_openshift_ansible_host]['vm_sources'] | default([], true) }}"
  when:
    - __e2e_testing_vm_source in groups['vm_sources']
    - "'vddk' in hostvars[__e2e_testing_vm_source]"
    - hostvars[__e2e_testing_vm_source]['vddk']['image'] | default('', true) | length > 0
    - hostvars[__e2e_testing_vm_source]['vddk']['username'] | default('', true) | length > 0
    - hostvars[__e2e_testing_vm_source]['vddk']['password'] | default('', true) | length > 0
...
