---

- name: Manage registry credentials for the target OpenShift cluster
  hosts: "{{ utility_clusters | default('migration_clusters') }}"
  gather_facts: false
  connection: local
  tasks:
    - name: Invoke utility_registry_credentials role
      ansible.builtin.include_role:
        name: infra.openshift_virtualization_migration.utility_registry_credentials
...
