---

- name: Determine utility clusters for AAP deployment
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Set utility_clusters to aap_clusters if group has hosts
      ansible.builtin.set_fact:
        utility_clusters: >-
          {{
            (groups['aap_clusters'] | default([]) | length > 0) |
              ternary('aap_clusters', 'migration_clusters')
          }}

- name: Deploy AAP
  ansible.builtin.import_playbook: utility_aap_deploy.yml
  vars:
    utility_clusters: "{{ hostvars['localhost']['utility_clusters'] }}"

- name: Add Ansible Group
  hosts: >-
    {{
      (groups['aap_clusters'] | default([]) | length > 0) |
        ternary('aap_clusters', 'migration_clusters')
    }}
  connection: local
  tasks:
    - name: Add hosts to Ansible group
      no_log: "{{ secure_logging | default(true) }}"
      ansible.builtin.add_host:
        name: "aap_{{ utility_clusters_host }}"
        groups: migration_aap
        aap_hostname: "https://{{ hostvars[utility_clusters_host]['__utility_aap_deploy_aap_hostname'] }}"
        aap_validate_certs: "{{ hostvars[utility_clusters_host]['__utility_aap_deploy_aap_validate_certs'] }}"
        aap_username: "{{ hostvars[utility_clusters_host]['__utility_aap_deploy_aap_username'] }}"
        aap_password: "{{ hostvars[utility_clusters_host]['__utility_aap_deploy_aap_password'] }}"
      loop_control:
        loop_var: utility_clusters_host
      loop: >-
        {{
          groups[
            (groups['aap_clusters'] | default([]) | length > 0) |
              ternary('aap_clusters', 'migration_clusters')
          ] | default([])
        }}

- name: Seed AAP
  ansible.builtin.import_playbook: vmf_seed_aap.yml

- name: Set Up Testing Namespace
  hosts: migration_clusters
  connection: local
  tasks:
    - name: Set up Namespace on migration cluster
      ansible.builtin.include_role:
        name: infra.openshift_virtualization_migration.e2e_testing
        tasks_from: namespace_prepare
      loop_control:
        loop_var: migration_aap_host
      when:
        - hostvars[inventory_hostname]['aap_hosts'] is defined
        - migration_aap_host in hostvars[inventory_hostname]['aap_hosts']
      loop: "{{ groups['migration_aap'] }}"

- name: Configure Registry Credentials
  hosts: migration_aap
  connection: local
  gather_facts: false
  tasks:
    - name: Configure VDDK Credentials if required
      ansible.builtin.include_role:
        name: infra.openshift_virtualization_migration.e2e_testing
        tasks_from: configure_vddk_credentials
      loop_control:
        loop_var: migration_cluster_host
      loop: "{{ groups['migration_clusters'] }}"
      when:
        - hostvars[migration_cluster_host]['aap_hosts'] is defined
        - inventory_hostname in hostvars[migration_cluster_host]['aap_hosts']
      vars:
        e2e_testing_openshift_ansible_host: "{{ migration_cluster_host }}"

- name: Execute Migration Activities
  hosts: migration_aap
  connection: local
  gather_facts: false
  tasks:
    - name: Run Migration activities against the migration clusters
      ansible.builtin.include_role:
        name: infra.openshift_virtualization_migration.e2e_testing
        tasks_from: run_openshift_cluster
      loop_control:
        loop_var: migration_cluster_host
      loop: >-
        {{
          groups['migration_clusters'] |
            map('extract', hostvars) |
            selectattr('aap_hosts', 'defined') |
            selectattr('aap_hosts', 'contains', inventory_hostname) |
            map(attribute='inventory_hostname')
        }}
      vars:
        e2e_testing_openshift_ansible_host: "{{ migration_cluster_host }}"
...
